{{- if and .Values.deployment.enabled .Values.deployment.autoscaling.enabled }}
{{- if .Capabilities.APIVersions.Has "autoscaling/v2beta1/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2beta1
{{- else }}
apiVersion: autoscaling/v2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "promtail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "promtail.fullname" . }}
  {{- with .Values.deployment.autoscaling }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- with .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
    {{- end }}
    {{- with .targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
