apiVersion: v1
kind: Service
metadata:
  name: opentracing-demo
spec:
  selector:
    app: opentracing-demo
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: frontend